services:
  mistify:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./Dockerfile
        - action: rebuild
          path: ./Dockerfile.base
