# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import operations_pb2 as mistify_dot_operations__pb2

GRPC_GENERATED_VERSION = '1.80.0'
try:
    GRPC_VERSION = grpc.__version__
except AttributeError:
    GRPC_VERSION = '1.80.0'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except (ImportError, AttributeError):
    _version_not_supported = False

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mistify/operations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MistifyOperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzePosts = channel.unary_unary(
                '/mistify.operations.MistifyOperations/AnalyzePosts',
                request_serializer=mistify_dot_operations__pb2.AnalyzePostsRequest.SerializeToString,
                response_deserializer=mistify_dot_operations__pb2.EnqueueAnalysisResponse.FromString,
                _registered_method=True)
        self.DetectLanguage = channel.unary_unary(
                '/mistify.operations.MistifyOperations/DetectLanguage',
                request_serializer=mistify_dot_operations__pb2.DetectLanguageRequest.SerializeToString,
                response_deserializer=mistify_dot_operations__pb2.EnqueueAnalysisResponse.FromString,
                _registered_method=True)
        self.ClassifyContent = channel.unary_unary(
                '/mistify.operations.MistifyOperations/ClassifyContent',
                request_serializer=mistify_dot_operations__pb2.ClassifyContentRequest.SerializeToString,
                response_deserializer=mistify_dot_operations__pb2.EnqueueAnalysisResponse.FromString,
                _registered_method=True)
        self.TranslateText = channel.unary_unary(
                '/mistify.operations.MistifyOperations/TranslateText',
                request_serializer=mistify_dot_operations__pb2.TranslateTextRequest.SerializeToString,
                response_deserializer=mistify_dot_operations__pb2.EnqueueAnalysisResponse.FromString,
                _registered_method=True)
        self.EmbedText = channel.unary_unary(
                '/mistify.operations.MistifyOperations/EmbedText',
                request_serializer=mistify_dot_operations__pb2.EmbedTextRequest.SerializeToString,
                response_deserializer=mistify_dot_operations__pb2.EnqueueAnalysisResponse.FromString,
                _registered_method=True)
        self.ClusterPost = channel.unary_unary(
                '/mistify.operations.MistifyOperations/ClusterPost',
                request_serializer=mistify_dot_operations__pb2.ClusterPostRequest.SerializeToString,
                response_deserializer=mistify_dot_operations__pb2.EnqueueAnalysisResponse.FromString,
                _registered_method=True)


class MistifyOperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzePosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectLanguage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranslateText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClusterPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MistifyOperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzePosts': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzePosts,
                    request_deserializer=mistify_dot_operations__pb2.AnalyzePostsRequest.FromString,
                    response_serializer=mistify_dot_operations__pb2.EnqueueAnalysisResponse.SerializeToString,
            ),
            'DetectLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectLanguage,
                    request_deserializer=mistify_dot_operations__pb2.DetectLanguageRequest.FromString,
                    response_serializer=mistify_dot_operations__pb2.EnqueueAnalysisResponse.SerializeToString,
            ),
            'ClassifyContent': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyContent,
                    request_deserializer=mistify_dot_operations__pb2.ClassifyContentRequest.FromString,
                    response_serializer=mistify_dot_operations__pb2.EnqueueAnalysisResponse.SerializeToString,
            ),
            'TranslateText': grpc.unary_unary_rpc_method_handler(
                    servicer.TranslateText,
                    request_deserializer=mistify_dot_operations__pb2.TranslateTextRequest.FromString,
                    response_serializer=mistify_dot_operations__pb2.EnqueueAnalysisResponse.SerializeToString,
            ),
            'EmbedText': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedText,
                    request_deserializer=mistify_dot_operations__pb2.EmbedTextRequest.FromString,
                    response_serializer=mistify_dot_operations__pb2.EnqueueAnalysisResponse.SerializeToString,
            ),
            'ClusterPost': grpc.unary_unary_rpc_method_handler(
                    servicer.ClusterPost,
                    request_deserializer=mistify_dot_operations__pb2.ClusterPostRequest.FromString,
                    response_serializer=mistify_dot_operations__pb2.EnqueueAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mistify.operations.MistifyOperations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mistify.operations.MistifyOperations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MistifyOperations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzePosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mistify.operations.MistifyOperations/AnalyzePosts',
            mistify_dot_operations__pb2.AnalyzePostsRequest.SerializeToString,
            mistify_dot_operations__pb2.EnqueueAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mistify.operations.MistifyOperations/DetectLanguage',
            mistify_dot_operations__pb2.DetectLanguageRequest.SerializeToString,
            mistify_dot_operations__pb2.EnqueueAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mistify.operations.MistifyOperations/ClassifyContent',
            mistify_dot_operations__pb2.ClassifyContentRequest.SerializeToString,
            mistify_dot_operations__pb2.EnqueueAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranslateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mistify.operations.MistifyOperations/TranslateText',
            mistify_dot_operations__pb2.TranslateTextRequest.SerializeToString,
            mistify_dot_operations__pb2.EnqueueAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mistify.operations.MistifyOperations/EmbedText',
            mistify_dot_operations__pb2.EmbedTextRequest.SerializeToString,
            mistify_dot_operations__pb2.EnqueueAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClusterPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mistify.operations.MistifyOperations/ClusterPost',
            mistify_dot_operations__pb2.ClusterPostRequest.SerializeToString,
            mistify_dot_operations__pb2.EnqueueAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MonitorIngestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveAnalysisResult = channel.unary_unary(
                '/mistify.operations.MonitorIngest/ReceiveAnalysisResult',
                request_serializer=mistify_dot_operations__pb2.AnalysisResultRequest.SerializeToString,
                response_deserializer=mistify_dot_operations__pb2.AnalysisResultResponse.FromString,
                _registered_method=True)


class MonitorIngestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveAnalysisResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveAnalysisResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveAnalysisResult,
                    request_deserializer=mistify_dot_operations__pb2.AnalysisResultRequest.FromString,
                    response_serializer=mistify_dot_operations__pb2.AnalysisResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mistify.operations.MonitorIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mistify.operations.MonitorIngest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MonitorIngest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveAnalysisResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mistify.operations.MonitorIngest/ReceiveAnalysisResult',
            mistify_dot_operations__pb2.AnalysisResultRequest.SerializeToString,
            mistify_dot_operations__pb2.AnalysisResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
