name: Build Base Image

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.base'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  build-and-push-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOYMENT_TOKEN }}

      - name: Build and push base Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.base
          push: true
          tags: ghcr.io/${{ github.repository }}-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
